
name: 'cost_savings'
version: '1.0.0'

profile: 'cost_savings'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  cost_savings:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
