cost_savings:
  target: dev
  outputs:
  # Local Environment
    dev:
      type: bigquery
      method: service-account
      project: cost-savings-tl
      dataset: analytics
      threads: 4
      timeout_seconds: 300
      location: US
      keyfile: bigquery-key.json

    # GitHub Actions Environment
    ci:
      type: bigquery
      method: oauth 
      project: cost-savings-tl
      dataset: analytics
      threads: 4
      timeout_seconds: 300
      location: US